@host=http://localhost:5299

POST {{host}}/auth/register
Content-Type:application/json

{
  "firstName":"Saidul Islam",
  "lastName":"Rajib",
  "email":"saidul.is.rajib@gmail.com",
  "password":"Test@123"
}